import type { Service } from "./types";

export const services: Service[] = [
  {
    slug: "digitalstrategie",
    category: "Strategie",
    navLabel: "Digitalstrategie",
    menuDescription: "Priorisierte Roadmap für Marke, Commerce und Automatisierung.",
    h1: "Digitalstrategie für Unternehmen, die wachsen wollen",
    metaTitle: "Digitalstrategie Agentur Köln | ONSET.digital",
    metaDescription:
      "Digitalstrategie aus einer Verantwortung: Analyse, priorisierte Roadmap und wirtschaftliche Zielgrößen für Marke, Commerce, CRM und Automatisierung.",
    primaryKeyword: "Digitalstrategie Agentur",
    secondaryKeywords: ["Digitalisierungsberatung", "digitale Transformation", "strategisches Sparring", "Technologieberatung"],
    heroKicker: "Strategie & Beratung",
    heroLead:
      "Bevor wir gestalten, entwickeln oder automatisieren, schaffen wir Klarheit: Wo steht Ihr Unternehmen digital, was bremst Wachstum, und welche Investition zahlt zuerst ein?",
    audience: [
      "Geschäftsführung mittelständischer Unternehmen ohne dokumentierte Digitalstrategie",
      "Unternehmen mit mehreren parallel laufenden Digitalprojekten ohne gemeinsame Linie",
      "Marken vor einer größeren Investitionsentscheidung wie Relaunch, neuem CRM oder Automatisierung",
    ],
    problems: [
      {
        title: "Maßnahmen ohne gemeinsamen Nenner",
        description:
          "Website, Kampagnen, CRM und Content werden unabhängig voneinander beauftragt und entwickeln sich in unterschiedliche Richtungen.",
      },
      {
        title: "Investitionen ohne belastbare Grundlage",
        description: "Budget wird vergeben, ohne dass klar ist, welche Maßnahme welchen wirtschaftlichen Hebel bewegt.",
      },
      {
        title: "Fehlende interne Verantwortlichkeit",
        description:
          "Niemand im Unternehmen hat Mandat oder Kapazität, digitale Entscheidungen strategisch zu bündeln und gegeneinander abzuwägen.",
      },
    ],
    consequences:
      "Ohne gemeinsame Strategie summieren sich Einzelmaßnahmen selten zu Wachstum. Stattdessen entstehen Doppelkosten, eine uneinheitliche Markenwirkung und Entscheidungen, die kurzfristig plausibel wirken, aber langfristig gegeneinander arbeiten.",
    deliverables: [
      { title: "Digital-Audit", description: "Bestandsaufnahme von Website oder Shop, CRM, Marketing-Systemen und Prozessen inklusive technischer und wirtschaftlicher Bewertung." },
      { title: "Priorisierte Roadmap", description: "Konkrete Reihenfolge der nächsten zwölf bis vierundzwanzig Monate, abgestimmt auf Budget, Team-Kapazität und Marktdruck." },
      { title: "Wirtschaftliche Zielgrößen", description: "Definierte Kennzahlen je Maßnahme, damit Erfolg messbar statt gefühlt bewertet wird." },
      { title: "Strategisches Sparring", description: "Regelmäßiger Austausch mit der Geschäftsführung als unabhängige strategische Instanz." },
    ],
    approach:
      "Wir beginnen nicht bei Kanälen oder Tools, sondern bei Ihrem Geschäftsmodell: Wo entsteht Umsatz, wo Reibung, wo Risiko? Aus dieser Analyse leiten wir ab, welche digitalen Systeme in welcher Reihenfolge Wirkung entfalten, und vermeiden Investitionen, die isoliert bleiben würden.",
    process: [
      { title: "Bestandsaufnahme", description: "Wir sichten bestehende Systeme, Daten und Prozesse und sprechen mit den relevanten Stakeholdern." },
      { title: "Potenzialbewertung", description: "Wir bewerten jeden Hebel nach wirtschaftlichem Potenzial, Aufwand und Abhängigkeiten." },
      { title: "Roadmap-Workshop", description: "Gemeinsam mit Ihrer Geschäftsführung priorisieren wir die Umsetzungsreihenfolge." },
      { title: "Begleitete Umsetzung", description: "Wir übergeben die Roadmap nicht, sondern verantworten die folgenden Schritte mit." },
    ],
    systems: ["Web-Analytics- und Tracking-Systeme", "CRM- und Marketing-Automation-Plattformen", "Roadmap- und Projektsteuerungstools", "gängige E-Commerce- und CMS-Architekturen"],
    advantages: [
      "Externe, unabhängige Einschätzung ohne Tool-Bias",
      "Strategie und spätere Umsetzung liegen in einer Verantwortung",
      "Priorisierung nach wirtschaftlicher Wirkung statt nach Trend",
      "Direkter Austausch auf Geschäftsführungsebene",
    ],
    relatedServiceSlugs: ["ki-automatisierung", "crm-prozesse", "webdesign-webentwicklung"],
    relatedSolutionSlugs: ["mittelstand", "ki-im-unternehmen"],
    caseStudySlug: "beispielprojekt-platzhalter",
    insightSlugs: ["shopify-relaunch-ablauf-kosten", "ki-automatisierung-im-mittelstand"],
    primaryCTA: "Digitalstrategie entwickeln",
    secondaryCTA: "Erstgespräch vereinbaren",
    faqs: [
      { question: "Ab welcher Unternehmensgröße lohnt sich eine Digitalstrategie?", answer: "Sinnvoll ist sie, sobald mehr als ein digitaler Kanal oder Dienstleister im Einsatz ist und Entscheidungen nicht mehr aus dem Bauch heraus getroffen werden sollen – unabhängig von der Mitarbeiterzahl." },
      { question: "Erstellen Sie die Strategie, ohne die Umsetzung zu übernehmen?", answer: "Auf Wunsch ja. In der Regel begleiten wir jedoch auch die Umsetzung, weil sich Strategie und Ausführung in unserer Erfahrung gegenseitig schärfen." },
      { question: "Wie lange dauert die Entwicklung einer Digitalstrategie?", answer: "Je nach Komplexität und Datenlage vier bis acht Wochen bis zur priorisierten Roadmap, danach begleitende Umsetzung in festgelegten Phasen." },
      { question: "Was kostet eine Digitalstrategie bei ONSET.digital?", answer: "Der Umfang richtet sich nach Unternehmensgröße und Anzahl der zu bewertenden Systeme. Den passenden Rahmen besprechen wir im kostenfreien Erstgespräch." },
    ],
    imagePlaceholders: {
      hero: {
        label: "Hero-Visual – Digitalstrategie",
        ratioDesktop: "21/9",
        ratioMobile: "4/5",
        motif: "Reduzierte Aufnahme einer Strategie- oder Priorisierungssitzung: Roadmap-Board, handschriftliche Priorisierung, keine gestellte Meeting-Situation",
        wirkung: "konzentriert, präzise, strategisch",
        funktion: "vermittelt den analytischen, planerischen Charakter der Leistung",
        type: "Fotografie",
        mobileNote: "Ausschnitt auf das Roadmap-Board zentrieren, Personen ggf. anschneiden",
      },
      application: {
        label: "Anwendungsbeispiel – Priorisierte Roadmap",
        ratioDesktop: "16/9",
        ratioMobile: "4/5",
        motif: "Individuell gestaltete Darstellung einer priorisierten Roadmap mit Zeitachse und Wirkungsgrad je Maßnahme",
        wirkung: "klar, strukturiert, nachvollziehbar",
        funktion: "macht das abstrakte Ergebnis der Leistung konkret sichtbar",
        type: "Grafik",
        mobileNote: "Zeitachse vertikal stapeln statt horizontal scrollen",
      },
      process: {
        label: "Prozessdarstellung – Von der Analyse zur Roadmap",
        ratioDesktop: "16/9",
        ratioMobile: "1/1",
        motif: "Eigenes, reduziertes Diagramm der vier Prozessschritte ohne generische Icon-Bibliothek",
        wirkung: "ruhig, orientierend",
        funktion: "gibt Orientierung über den Ablauf der Zusammenarbeit",
        type: "Grafik",
        mobileNote: "Schritte untereinander anordnen",
      },
    },
  },
  {
    slug: "e-commerce-shopify",
    category: "Commerce & Web",
    navLabel: "E-Commerce & Shopify",
    menuDescription: "Shopify-Shops und E-Commerce-Systeme, die verkaufen.",
    h1: "E-Commerce- und Shopify-Agentur für Marken mit Wachstumsanspruch",
    metaTitle: "Shopify-Agentur Köln | E-Commerce-Agentur | ONSET.digital",
    metaDescription:
      "Shopify-Shops und E-Commerce-Systeme, die Marke, Conversion und Prozesse verbinden. Relaunch, Neuentwicklung und laufende Optimierung aus einer Verantwortung.",
    primaryKeyword: "Shopify-Agentur Köln",
    secondaryKeywords: ["E-Commerce-Agentur", "Onlineshop erstellen lassen", "Shopify-Relaunch", "Shopify-Migration", "Conversion-Optimierung"],
    heroKicker: "E-Commerce & Shopify",
    heroLead:
      "Ein Onlineshop ist kein Design-Projekt, sondern ein Verkaufssystem. Wir entwickeln Shopify-Shops, die Marke, Conversion, Zahlungs- und Versandprozesse sowie Schnittstellen zusammendenken.",
    audience: [
      "Onlinehändler mit wachsendem Sortiment und steigenden Anforderungen an Performance",
      "Marken vor einem Wechsel zu Shopify oder einem Shopify-Relaunch",
      "Stationäre Händler, die einen belastbaren Online-Vertriebskanal aufbauen wollen",
    ],
    problems: [
      { title: "Shop wächst nicht mit dem Sortiment mit", description: "Struktur, Ladezeit und Kategorisierung wurden nicht für die heutige Sortimentsgröße gedacht." },
      { title: "Conversion bleibt hinter dem Traffic zurück", description: "Der Shop generiert Besuche, aber Checkout, Produktseiten oder Vertrauenssignale bremsen den Abschluss." },
      { title: "Schnittstellen laufen manuell oder instabil", description: "Zahlungs-, Versand- und Bestandsdaten werden nicht zuverlässig zwischen den Systemen synchronisiert." },
    ],
    consequences:
      "Jeder Punkt Reibung im Kaufprozess kostet unmittelbar Umsatz. Instabile Schnittstellen erzeugen zusätzlich manuellen Aufwand im Tagesgeschäft und Fehler, die Kundenvertrauen kosten.",
    deliverables: [
      { title: "Shopify-Entwicklung", description: "Individuelles Theme- und Storefront-Development statt austauschbarer Templates." },
      { title: "Shopify-Relaunch und -Migration", description: "Strukturierter Wechsel zu Shopify oder Neuaufbau eines bestehenden Shops inklusive SEO-sicherer URL-Führung." },
      { title: "Conversion-Optimierung", description: "Systematische Verbesserung von Produktseiten, Checkout und Vertrauenselementen auf Basis von Nutzungsdaten." },
      { title: "System- und Schnittstellenintegration", description: "Anbindung von Zahlungsanbietern, Versanddienstleistern, CRM und Marketing-Tools." },
    ],
    approach:
      "Wir betrachten Ihren Shop als Teil eines größeren Systems aus Marke, CRM und Marketing. Entscheidungen zu Struktur, Design und Technik werden daher nicht isoliert getroffen, sondern konsequent auf Conversion und Skalierbarkeit ausgerichtet.",
    process: [
      { title: "Shop-Audit", description: "Technische, gestalterische und conversion-relevante Analyse des bestehenden Shops oder der Ausgangslage." },
      { title: "Struktur & UX-Konzept", description: "Kategorien, Navigation und Checkout-Flow werden vor dem visuellen Design festgelegt." },
      { title: "Design & Entwicklung", description: "Umsetzung in Shopify mit individuellem Storefront-Code statt Standard-Theme." },
      { title: "Launch & Optimierung", description: "Kontrollierter Go-live und datenbasierte Weiterentwicklung nach dem Launch." },
    ],
    systems: ["Shopify und Shopify Plus", "Zahlungsanbieter wie gängige PSP-Lösungen", "Versand- und Fulfillment-Schnittstellen", "Analytics- und Conversion-Tracking-Tools"],
    advantages: [
      "Individuelle Storefront-Entwicklung statt Baukasten-Theme",
      "Conversion, Design und Technik werden gemeinsam verantwortet",
      "SEO-sichere Migration ohne Sichtbarkeitsverlust",
      "Laufende Betreuung statt einmaligem Launch",
    ],
    relatedServiceSlugs: ["webdesign-webentwicklung", "seo-ki-sichtbarkeit", "crm-prozesse"],
    relatedSolutionSlugs: ["e-commerce-unternehmen", "shopify-unternehmen"],
    caseStudySlug: "beispielprojekt-platzhalter",
    insightSlugs: ["shopify-relaunch-ablauf-kosten"],
    primaryCTA: "Shopify-Projekt besprechen",
    secondaryCTA: "Erstgespräch vereinbaren",
    faqs: [
      { question: "Was kostet ein Shopify-Relaunch?", answer: "Das hängt von Sortimentsgröße, Individualisierungsgrad und Schnittstellen ab. Nach einem kurzen Shop-Audit erhalten Sie einen konkreten, unverbindlichen Rahmen." },
      { question: "Wie lange dauert ein Shopify-Projekt?", answer: "Ein fokussierter Relaunch dauert in der Regel sechs bis zwölf Wochen, eine komplexere Neuentwicklung mit vielen Schnittstellen entsprechend länger." },
      { question: "Übernehmen Sie auch die Migration von einem anderen Shopsystem?", answer: "Ja. Wir planen die Migration so, dass Rankings, Produktdaten und Kundendaten sauber und ohne Sichtbarkeitsverlust übernommen werden." },
      { question: "Betreuen Sie den Shop auch nach dem Launch weiter?", answer: "Ja, über planbare Betreuungskontingente für technische Weiterentwicklung, Conversion-Optimierung und Support." },
    ],
    imagePlaceholders: {
      hero: {
        label: "Hero-Visual – E-Commerce & Shopify",
        ratioDesktop: "21/9",
        ratioMobile: "4/5",
        motif: "Reales Shopify-Shopinterface eines Projekts in reduzierter, editorialer Bildkomposition – Produktseite oder Kategorieübersicht",
        wirkung: "hochwertig, verkaufsstark, präzise",
        funktion: "zeigt sofort die Kompetenz im Shopify-Umfeld anhand echter Interfaces",
        type: "Mock-up",
        mobileNote: "Mobile Produktansicht als eigenen Ausschnitt zeigen",
      },
      application: {
        label: "Anwendungsbeispiel – Checkout & Produktseite",
        ratioDesktop: "16/9",
        ratioMobile: "4/5",
        motif: "Nebeneinanderstellung von Desktop- und Mobile-Ansicht eines Checkout-Flows aus einem realen Projekt",
        wirkung: "konkret, vertrauenswürdig",
        funktion: "belegt die Umsetzungsqualität an einem nachvollziehbaren Beispiel",
        type: "Mock-up",
        mobileNote: "Nur die mobile Ansicht zeigen, Desktop-Ansicht auf Anfrage/Case Study verlinken",
      },
      process: {
        label: "Prozessdarstellung – Vom Audit zum Launch",
        ratioDesktop: "16/9",
        ratioMobile: "1/1",
        motif: "Individuelles Ablaufdiagramm der vier Projektphasen",
        wirkung: "strukturiert, verlässlich",
        funktion: "reduziert Unsicherheit bezüglich Ablauf und Aufwand",
        type: "Grafik",
        mobileNote: "Vertikale Anordnung der Phasen",
      },
    },
  },
  {
    slug: "webdesign-webentwicklung",
    category: "Commerce & Web",
    navLabel: "Webdesign & Webentwicklung",
    menuDescription: "Websites und digitale Plattformen mit klarer UX.",
    h1: "Webdesign und Webentwicklung für Marken mit Substanz",
    metaTitle: "Webdesign-Agentur Köln | Website erstellen lassen | ONSET.digital",
    metaDescription:
      "Individuelles Webdesign und individuelle Webentwicklung: UX-Konzeption, Gestaltung und technischer Aufbau aus einer Verantwortung – für Websites, die Positionierung und Performance verbinden.",
    primaryKeyword: "Webdesign-Agentur Köln",
    secondaryKeywords: ["Website erstellen lassen", "Website-Relaunch-Agentur", "UX-Design-Agentur", "individuelle Webentwicklung"],
    heroKicker: "Websites & digitale Plattformen",
    heroLead:
      "Ihre Website ist häufig der erste ernsthafte Kontakt mit Ihrem Unternehmen. Wir entwickeln Websites, die Positionierung, Nutzerführung und technische Performance konsequent zusammenbringen.",
    audience: [
      "Unternehmen mit einer Website, die nicht mehr zur eigentlichen Marktposition passt",
      "Marken vor einem Rebranding oder einer strategischen Neuausrichtung",
      "Unternehmen, die eine wachsende Zahl an Landingpages und Inhalten strukturiert abbilden müssen",
    ],
    problems: [
      { title: "Website spiegelt die eigentliche Qualität nicht wider", description: "Fachliche Kompetenz und digitale Außenwirkung klaffen spürbar auseinander." },
      { title: "Unklare Struktur und Nutzerführung", description: "Besucher finden relevante Inhalte nicht innerhalb weniger Klicks, Anfragen bleiben aus." },
      { title: "Technische Basis begrenzt Wachstum", description: "Ladezeit, Erweiterbarkeit oder Content-Pflege sind mit dem bestehenden System kaum wirtschaftlich möglich." },
    ],
    consequences:
      "Eine Website, die nicht überzeugt, kostet nicht nur Anfragen, sondern auch Vertrauen in kommende Angebote. Technische Limitierungen erzeugen zusätzlich laufenden Mehraufwand bei jeder inhaltlichen Änderung.",
    deliverables: [
      { title: "UX- und Informationsarchitektur", description: "Struktur und Nutzerführung werden vor dem visuellen Design festgelegt und getestet." },
      { title: "UI-Design", description: "Individuelles visuelles Design auf Basis Ihrer Markenidentität, nicht aus einem Baukasten." },
      { title: "Individuelle Webentwicklung", description: "Technischer Aufbau nach Ihren Anforderungen an Performance, Erweiterbarkeit und Content-Pflege." },
      { title: "Landingpages", description: "Konversionsstarke Einzelseiten für Kampagnen, Angebote oder neue Zielgruppen." },
    ],
    approach:
      "Wir gestalten nicht zuerst und strukturieren danach, sondern umgekehrt: Inhalte, Nutzerführung und Zielhandlungen werden konzipiert, bevor die visuelle Gestaltung beginnt. So bleibt die Website auch bei künftigem Wachstum erweiterbar.",
    process: [
      { title: "Content- & UX-Audit", description: "Analyse bestehender Inhalte, Nutzerpfade und technischer Basis." },
      { title: "Strukturkonzept", description: "Sitemap, Seitentypen und Nutzerführung werden festgelegt und intern abgestimmt." },
      { title: "Design & Entwicklung", description: "Individuelles UI-Design und technische Umsetzung in enger Abstimmung." },
      { title: "Technische Wartung & Weiterentwicklung", description: "Laufende Pflege, Performance-Kontrolle und inhaltliche Erweiterung nach dem Launch." },
    ],
    systems: ["moderne Headless- und CMS-Architekturen", "Performance- und Core-Web-Vitals-Monitoring", "Barrierefreiheits-Prüfwerkzeuge", "Analytics- und Heatmap-Tools"],
    advantages: [
      "Individuelles UX-Konzept statt vorgefertigtem Layout",
      "Technik wird auf Erweiterbarkeit statt kurzfristige Lösung ausgelegt",
      "Design zahlt konsequent auf Positionierung und Conversion ein",
      "Kontinuierliche Weiterentwicklung statt Projektabschluss",
    ],
    relatedServiceSlugs: ["branding-content", "seo-ki-sichtbarkeit", "e-commerce-shopify"],
    relatedSolutionSlugs: ["website-relaunch", "mittelstand"],
    caseStudySlug: "beispielprojekt-platzhalter",
    insightSlugs: ["shopify-relaunch-ablauf-kosten"],
    primaryCTA: "Relaunch planen",
    secondaryCTA: "Website-Projekt anfragen",
    faqs: [
      { question: "Arbeiten Sie mit bestehenden Content-Management-Systemen?", answer: "Ja. Wir wählen das System nach Ihren Anforderungen an Pflegbarkeit, Performance und Erweiterbarkeit aus – individuell entwickelt oder auf einer geeigneten CMS-Basis." },
      { question: "Wie lange dauert ein Website-Relaunch?", answer: "Je nach Umfang acht bis vierzehn Wochen von der Strukturkonzeption bis zum Launch." },
      { question: "Wird die neue Website für Suchmaschinen optimiert?", answer: "Technisches SEO ist fester Bestandteil der Entwicklung, keine nachgelagerte Zusatzleistung." },
      { question: "Bleibt die Website nach dem Launch erweiterbar?", answer: "Ja, das ist ein zentrales Ziel der technischen Konzeption – neue Seiten und Inhalte lassen sich ohne Neuentwicklung ergänzen." },
    ],
    imagePlaceholders: {
      hero: {
        label: "Hero-Visual – Webdesign & Webentwicklung",
        ratioDesktop: "21/9",
        ratioMobile: "4/5",
        motif: "Hochwertiges Website-Mock-up eines realen Projekts in reduzierter Bildkomposition, z. B. Ausschnitt einer Startseite",
        wirkung: "editorial, präzise, gestalterisch anspruchsvoll",
        funktion: "vermittelt den Gestaltungsanspruch der Leistung unmittelbar",
        type: "Mock-up",
        mobileNote: "Ausschnitt auf den oberen Seitenbereich (Hero) reduzieren",
      },
      application: {
        label: "Anwendungsbeispiel – Layoutdetail",
        ratioDesktop: "16/9",
        ratioMobile: "4/5",
        motif: "Detailaufnahme eines Layoutbereichs (Typografie, Raster, Abstände) aus einem realen Projekt",
        wirkung: "präzise, hochwertig",
        funktion: "zeigt gestalterische Sorgfalt im Detail",
        type: "Mock-up",
        mobileNote: "Einzelnes Detail statt Gesamtansicht zeigen",
      },
      process: {
        label: "Prozessdarstellung – Vom Audit zum Launch",
        ratioDesktop: "16/9",
        ratioMobile: "1/1",
        motif: "Eigenes Ablaufdiagramm der vier Projektphasen",
        wirkung: "strukturiert, orientierend",
        funktion: "gibt Orientierung über Ablauf und Aufwand",
        type: "Grafik",
        mobileNote: "Vertikale Anordnung der Phasen",
      },
    },
  },
  {
    slug: "ki-automatisierung",
    category: "KI, CRM & Prozesse",
    navLabel: "KI & Automatisierung",
    menuDescription: "KI-Agenten und Automatisierung für reale Prozesse.",
    h1: "KI-Automatisierung für Unternehmen mit realem Anwendungsfall",
    metaTitle: "KI-Agentur Köln | KI-Automatisierung für Unternehmen | ONSET.digital",
    metaDescription:
      "KI-Beratung und KI-Automatisierung für konkrete Anwendungsfälle: Vertrieb, Kundenservice und interne Prozesse. Keine Effekthascherei, sondern wirtschaftlich sinnvolle Automatisierung.",
    primaryKeyword: "KI-Agentur Köln",
    secondaryKeywords: ["KI-Beratung für Unternehmen", "KI-Automatisierung", "KI-Agenten für Unternehmen", "Workflow-Automatisierung", "Prozessautomatisierung"],
    heroKicker: "KI & Automatisierung",
    heroLead:
      "Wir setzen KI dort ein, wo sie einen nachvollziehbaren wirtschaftlichen Effekt hat: bei wiederkehrenden Aufgaben in Vertrieb, Kundenservice und internen Abläufen.",
    audience: [
      "Unternehmen mit wachsendem Auftragsvolumen bei gleichbleibender Teamgröße",
      "Vertriebs- und Serviceteams mit hohem Anteil an manuellen, wiederkehrenden Aufgaben",
      "Geschäftsführungen, die KI sinnvoll statt symbolisch einsetzen möchten",
    ],
    problems: [
      { title: "Wachstum erzeugt Mehrarbeit statt Marge", description: "Mehr Anfragen und Aufträge führen unmittelbar zu mehr manuellem Aufwand statt zu Skaleneffekten." },
      { title: "Unklarheit über sinnvolle KI-Anwendungsfälle", description: "Es besteht Interesse an KI, aber keine belastbare Einschätzung, wo sie wirtschaftlich sinnvoll ist." },
      { title: "Insellösungen ohne Systemanbindung", description: "Einzelne KI-Tools werden ausprobiert, ohne an CRM, Website oder bestehende Prozesse angebunden zu sein." },
    ],
    consequences:
      "Ohne saubere Priorisierung entstehen entweder teure Insellösungen mit begrenztem Nutzen oder es bleibt bei unverbindlichem Ausprobieren. Beides bindet Zeit, ohne die eigentliche Kapazitätsknappheit zu lösen.",
    deliverables: [
      { title: "KI-Potenzialanalyse", description: "Systematische Bewertung, welche Prozesse sich wirtschaftlich sinnvoll automatisieren lassen." },
      { title: "KI-Agenten für Unternehmen", description: "Individuell konfigurierte Assistenzsysteme für Kundenservice, Vertrieb oder interne Anfragen." },
      { title: "Workflow- und Prozessautomatisierung", description: "Verknüpfung bestehender Systeme, damit wiederkehrende Abläufe ohne manuelle Übergabe funktionieren." },
      { title: "Vertriebs- und Marketing-Automatisierung", description: "Automatisierte Lead-Qualifizierung, Nachfassprozesse und Kommunikationsabläufe." },
    ],
    approach:
      "Wir starten mit den Prozessen, die heute am meisten Zeit binden, nicht mit der Technologie. Erst wenn der wirtschaftliche Nutzen eines Anwendungsfalls klar ist, wählen wir die passende technische Umsetzung – nachvollziehbar, überprüfbar und an Ihre bestehenden Systeme angebunden.",
    process: [
      { title: "Prozessanalyse", description: "Wir identifizieren wiederkehrende, zeitintensive Abläufe mit Automatisierungspotenzial." },
      { title: "Potenzialbewertung", description: "Jeder Anwendungsfall wird nach wirtschaftlichem Nutzen und Umsetzbarkeit bewertet." },
      { title: "Pilotumsetzung", description: "Der wirkungsvollste Anwendungsfall wird zuerst umgesetzt und in der Praxis geprüft." },
      { title: "Skalierung", description: "Bewährte Automatisierungen werden auf weitere Prozesse und Teams ausgeweitet." },
    ],
    systems: ["CRM- und Ticketing-Systeme", "Workflow-Automatisierungsplattformen", "Sprachmodell-gestützte Assistenzsysteme", "Schnittstellen zu Website, Shop und internen Tools"],
    advantages: [
      "Automatisierung nach wirtschaftlichem Nutzen priorisiert, nicht nach Trend",
      "Anbindung an bestehende Systeme statt isolierter Insellösung",
      "Transparente, nachvollziehbare Funktionsweise statt Blackbox",
      "Begleitung von der Potenzialanalyse bis zum laufenden Betrieb",
    ],
    relatedServiceSlugs: ["crm-prozesse", "digitalstrategie", "seo-ki-sichtbarkeit"],
    relatedSolutionSlugs: ["ki-im-unternehmen", "mittelstand"],
    caseStudySlug: "beispielprojekt-platzhalter",
    insightSlugs: ["ki-automatisierung-im-mittelstand"],
    primaryCTA: "Automatisierungspotenziale entdecken",
    secondaryCTA: "Erstgespräch vereinbaren",
    faqs: [
      { question: "Lohnt sich KI-Automatisierung auch für kleinere Teams?", answer: "Ja, häufig sogar besonders: Kleine Teams profitieren am stärksten davon, wiederkehrende Aufgaben nicht manuell erledigen zu müssen." },
      { question: "Ersetzen KI-Agenten Mitarbeitende im Kundenservice?", answer: "Ziel ist die Entlastung bei wiederkehrenden Anfragen, nicht der vollständige Ersatz. Komplexe oder sensible Fälle bleiben bei Ihrem Team." },
      { question: "Wie gehen Sie mit Datenschutz bei KI-Anwendungen um?", answer: "Wir prüfen Datenflüsse und Systemwahl im Rahmen der Potenzialanalyse und stimmen die Umsetzung mit Ihren Datenschutzanforderungen ab." },
      { question: "Wie schnell zeigt sich der Effekt einer Automatisierung?", answer: "Bei klar abgegrenzten Prozessen ist der Effekt häufig innerhalb weniger Wochen nach dem Pilotstart sichtbar." },
    ],
    imagePlaceholders: {
      hero: {
        label: "Hero-Visual – KI & Automatisierung",
        ratioDesktop: "21/9",
        ratioMobile: "4/5",
        motif: "Verständliche Darstellung eines realen automatisierten Ablaufs (z. B. Anfrage bis Antwort) statt abstrakter KI-Symbolik",
        wirkung: "klar, sachlich, vertrauenswürdig",
        funktion: "macht den konkreten Nutzen der Automatisierung nachvollziehbar",
        type: "Grafik",
        mobileNote: "Ablauf auf die wichtigsten drei Stationen reduzieren",
      },
      application: {
        label: "Anwendungsbeispiel – Automatisierter Prozess",
        ratioDesktop: "16/9",
        ratioMobile: "4/5",
        motif: "Reale Prozessdarstellung eines automatisierten Vertriebs- oder Serviceablaufs mit Systemanbindung",
        wirkung: "konkret, nachvollziehbar",
        funktion: "zeigt, wie Automatisierung in der Praxis funktioniert",
        type: "Grafik",
        mobileNote: "Einzelne Prozessstationen vertikal stapeln",
      },
      process: {
        label: "Prozessdarstellung – Von der Analyse zur Skalierung",
        ratioDesktop: "16/9",
        ratioMobile: "1/1",
        motif: "Eigenes Diagramm der vier Umsetzungsphasen",
        wirkung: "strukturiert, ruhig",
        funktion: "reduziert Unsicherheit bezüglich Umsetzung und Risiko",
        type: "Grafik",
        mobileNote: "Vertikale Anordnung der Phasen",
      },
    },
  },
  {
    slug: "crm-prozesse",
    category: "KI, CRM & Prozesse",
    navLabel: "CRM & Prozesse",
    menuDescription: "CRM-Einführung und Prozessoptimierung für Vertrieb & Service.",
    h1: "CRM-Beratung und Prozessoptimierung für skalierbaren Vertrieb",
    metaTitle: "CRM-Beratung & CRM-Einführung | ONSET.digital",
    metaDescription:
      "CRM-Einführung, CRM-Optimierung und Vertriebsautomatisierung: Wir strukturieren Leadmanagement und Kundenprozesse, damit Wachstum nicht an manueller Arbeit scheitert.",
    primaryKeyword: "CRM-Beratung",
    secondaryKeywords: ["CRM-Einführung", "CRM-Optimierung", "Leadmanagement", "Vertriebsautomatisierung", "Vertriebsprozesse"],
    heroKicker: "CRM & Prozesse",
    heroLead:
      "Ein CRM ist nur so gut wie die Prozesse dahinter. Wir strukturieren Leadmanagement, Vertriebs- und Serviceprozesse und richten Ihr CRM daran aus – nicht umgekehrt.",
    audience: [
      "Unternehmen ohne einheitliches System für Leads und Kundenkommunikation",
      "Vertriebsteams mit uneinheitlicher Nachverfolgung von Anfragen und Angeboten",
      "Unternehmen vor der Einführung oder Ablösung eines bestehenden CRM-Systems",
    ],
    problems: [
      { title: "Leads gehen im Tagesgeschäft unter", description: "Anfragen werden per E-Mail, Telefon und Formular verteilt erfasst, ohne einheitliche Nachverfolgung." },
      { title: "CRM wird nicht konsequent genutzt", description: "Ein System ist vorhanden, wird aber nicht in die täglichen Abläufe integriert." },
      { title: "Vertriebsprozesse sind nicht dokumentiert", description: "Erfolgreiche Abläufe hängen an einzelnen Personen statt an einem nachvollziehbaren Prozess." },
    ],
    consequences:
      "Unklare Leadprozesse kosten unmittelbar Umsatz durch verzögerte oder ausbleibende Nachverfolgung. Fehlt die Dokumentation von Vertriebsprozessen, wird Wachstum zusätzlich von der Verfügbarkeit einzelner Mitarbeitender abhängig.",
    deliverables: [
      { title: "CRM-Auswahl und -Einführung", description: "Auswahl und Implementierung eines CRM-Systems entlang Ihrer tatsächlichen Vertriebs- und Serviceprozesse." },
      { title: "CRM-Optimierung", description: "Strukturierung bestehender CRM-Systeme, die im Alltag nicht ausreichend genutzt werden." },
      { title: "Leadmanagement", description: "Einheitliche Erfassung, Qualifizierung und Nachverfolgung von Anfragen über alle Kanäle." },
      { title: "Automatisierte Kundenkommunikation", description: "Standardisierte, teilautomatisierte Kommunikationsstrecken für wiederkehrende Anlässe." },
    ],
    approach:
      "Wir beginnen mit der Prozessanalyse, nicht mit der Systemauswahl. So stellen wir sicher, dass das CRM Ihre tatsächliche Arbeitsweise abbildet, statt Ihr Team an ein starres System anzupassen.",
    process: [
      { title: "Prozessaufnahme", description: "Wir dokumentieren bestehende Vertriebs- und Serviceabläufe gemeinsam mit Ihrem Team." },
      { title: "System- und Strukturkonzept", description: "Festlegung von Datenmodell, Zuständigkeiten und Automatisierungsstufen." },
      { title: "Einführung & Schulung", description: "Implementierung des Systems und praxisnahe Einarbeitung Ihres Teams." },
      { title: "Laufende Optimierung", description: "Regelmäßige Überprüfung von Nutzung und Wirksamkeit nach der Einführung." },
    ],
    systems: ["gängige CRM-Plattformen", "Marketing-Automation-Systeme", "Ticketing- und Serviceplattformen", "Schnittstellen zu Website, Shop und E-Mail-Systemen"],
    advantages: [
      "Prozess vor System: Das CRM folgt Ihrer Arbeitsweise, nicht umgekehrt",
      "Einheitliche Nachverfolgung über alle Kontaktkanäle",
      "Schulung und Einführung als fester Bestandteil, nicht optionale Zusatzleistung",
      "Anbindung an Website, Shop und Automatisierung aus einer Hand",
    ],
    relatedServiceSlugs: ["ki-automatisierung", "digitalstrategie", "e-commerce-shopify"],
    relatedSolutionSlugs: ["mittelstand", "ki-im-unternehmen"],
    caseStudySlug: "beispielprojekt-platzhalter",
    insightSlugs: ["ki-automatisierung-im-mittelstand"],
    primaryCTA: "CRM-Projekt besprechen",
    secondaryCTA: "Erstgespräch vereinbaren",
    faqs: [
      { question: "Welches CRM-System empfehlen Sie?", answer: "Das hängt von Vertriebsprozess, Teamgröße und vorhandenen Systemen ab. Wir empfehlen erst nach der Prozessanalyse, nicht vorab." },
      { question: "Wir haben bereits ein CRM, das kaum genutzt wird – können Sie helfen?", answer: "Ja, das ist einer der häufigsten Ausgangspunkte. Meist liegt es an fehlender Prozessanbindung, nicht am System selbst." },
      { question: "Wie lange dauert eine CRM-Einführung?", answer: "Für ein mittelständisches Vertriebsteam realistisch sechs bis zehn Wochen inklusive Schulung." },
      { question: "Übernehmen Sie auch die Datenmigration aus dem alten System?", answer: "Ja, die saubere Übernahme bestehender Kunden- und Leaddaten ist fester Bestandteil der Einführung." },
    ],
    imagePlaceholders: {
      hero: {
        label: "Hero-Visual – CRM & Prozesse",
        ratioDesktop: "21/9",
        ratioMobile: "4/5",
        motif: "Nachvollziehbare Darstellung einer Customer Journey vom Erstkontakt bis zum Abschluss",
        wirkung: "strukturiert, verständlich",
        funktion: "macht den Nutzen strukturierter Prozesse sofort erkennbar",
        type: "Grafik",
        mobileNote: "Journey auf drei bis vier Kernstationen reduzieren",
      },
      application: {
        label: "Anwendungsbeispiel – Leadprozess",
        ratioDesktop: "16/9",
        ratioMobile: "4/5",
        motif: "Reale, anonymisierte Darstellung eines strukturierten Leadmanagement-Prozesses",
        wirkung: "konkret, glaubwürdig",
        funktion: "belegt die praktische Umsetzbarkeit der Leistung",
        type: "Grafik",
        mobileNote: "Einzelne Prozessschritte vertikal anordnen",
      },
      process: {
        label: "Prozessdarstellung – Von der Aufnahme zur Optimierung",
        ratioDesktop: "16/9",
        ratioMobile: "1/1",
        motif: "Eigenes Diagramm der vier Umsetzungsphasen",
        wirkung: "ruhig, orientierend",
        funktion: "gibt Sicherheit über Ablauf und Aufwand",
        type: "Grafik",
        mobileNote: "Vertikale Anordnung der Phasen",
      },
    },
  },
  {
    slug: "seo-ki-sichtbarkeit",
    category: "Sichtbarkeit & Marketing",
    navLabel: "SEO & KI-Sichtbarkeit",
    menuDescription: "Sichtbarkeit in klassischer und generativer Suche.",
    h1: "SEO und KI-Sichtbarkeit für nachhaltige organische Reichweite",
    metaTitle: "SEO-Agentur Köln | E-Commerce-SEO & KI-Sichtbarkeit | ONSET.digital",
    metaDescription:
      "SEO-Agentur für technische, inhaltliche und E-Commerce-SEO sowie Sichtbarkeit in generativen Suchsystemen. Nachhaltiger Aufbau statt kurzfristiger Rankingtricks.",
    primaryKeyword: "SEO-Agentur Köln",
    secondaryKeywords: ["E-Commerce-SEO", "Shopify-SEO", "KI-SEO", "Generative Engine Optimization", "technische SEO"],
    heroKicker: "SEO & digitale Sichtbarkeit",
    heroLead:
      "Sichtbarkeit entsteht heute in klassischer Suche und zunehmend in generativen Suchsystemen. Wir bauen beides auf einer sauberen technischen und inhaltlichen Basis auf.",
    audience: [
      "Unternehmen mit geringer organischer Sichtbarkeit trotz starker Marktposition",
      "Onlinehändler mit technischen SEO-Defiziten im Shopsystem",
      "Marken, die frühzeitig für KI-Suchsysteme und generative Suchergebnisse sichtbar werden wollen",
    ],
    problems: [
      { title: "Technische Basis bremst Sichtbarkeit", description: "Ladezeit, Struktur oder fehlerhafte Auszeichnung verhindern gutes Ranking trotz relevanter Inhalte." },
      { title: "Inhalte beantworten Suchintention nicht präzise", description: "Seiten sind vorhanden, treffen aber nicht, wonach die Zielgruppe tatsächlich sucht." },
      { title: "Keine Strategie für KI-Suchsysteme", description: "Klassische SEO wird betrieben, generative Suchergebnisse und KI-Antworten bleiben unberücksichtigt." },
    ],
    consequences:
      "Geringe organische Sichtbarkeit bedeutet dauerhafte Abhängigkeit von bezahltem Traffic. Wird die Sichtbarkeit in KI-Suchsystemen heute nicht mitgedacht, entsteht ein Nachteil, der sich mit wachsender Bedeutung generativer Suche verstärkt.",
    deliverables: [
      { title: "Technische SEO", description: "Behebung struktureller und performancebezogener Probleme als Grundlage jeder weiteren Maßnahme." },
      { title: "Onpage- und Content-SEO", description: "Ausrichtung von Inhalten auf reale Suchintentionen statt auf einzelne Keywords." },
      { title: "E-Commerce- und Shopify-SEO", description: "Kategorien-, Produkt- und Filterstruktur werden SEO-gerecht aufgebaut, ohne Nutzerführung zu beeinträchtigen." },
      { title: "KI-Sichtbarkeit / Generative Engine Optimization", description: "Inhaltliche und strukturelle Optimierung für Zitierfähigkeit in KI-generierten Suchantworten." },
    ],
    approach:
      "Wir priorisieren technische Grundlagen vor inhaltlicher Erweiterung: Erst wenn Struktur, Ladezeit und Auszeichnung stimmen, entfalten Inhalte ihre volle Wirkung – in klassischer wie in generativer Suche.",
    process: [
      { title: "SEO-Audit", description: "Technische, inhaltliche und strukturelle Analyse des Status quo." },
      { title: "Themen- und Intentionsplanung", description: "Ableitung von Themenclustern entlang realer Suchintentionen Ihrer Zielgruppe." },
      { title: "Umsetzung", description: "Technische Fixes, Content-Optimierung und strukturierte Daten werden priorisiert umgesetzt." },
      { title: "Laufende Betreuung", description: "Monitoring, Nachschärfung und kontinuierlicher Ausbau der Themencluster." },
    ],
    systems: ["Search-Console- und Ranking-Monitoring", "Core-Web-Vitals-Analysewerkzeuge", "strukturierte Daten (Schema.org)", "Content- und Themencluster-Planung"],
    advantages: [
      "Technische Basis vor inhaltlicher Erweiterung",
      "Themencluster statt isolierter Einzelseiten",
      "Vorbereitung auf klassische und generative Suche gleichermaßen",
      "Laufende Betreuung statt einmaligem Projekt",
    ],
    relatedServiceSlugs: ["branding-content", "google-ads-performance", "e-commerce-shopify"],
    relatedSolutionSlugs: ["e-commerce-unternehmen", "mittelstand"],
    caseStudySlug: "beispielprojekt-platzhalter",
    insightSlugs: ["shopify-relaunch-ablauf-kosten"],
    primaryCTA: "Sichtbarkeit analysieren lassen",
    secondaryCTA: "Erstgespräch vereinbaren",
    faqs: [
      { question: "Was ist Generative Engine Optimization?", answer: "Die Optimierung von Inhalten und Struktur, damit sie in KI-generierten Suchantworten (z. B. KI-Übersichten) zuverlässig zitiert werden." },
      { question: "Wie lange dauert es, bis SEO-Maßnahmen wirken?", answer: "Technische Verbesserungen zeigen sich oft innerhalb weniger Wochen, inhaltlicher Aufbau von Themenautorität benötigt in der Regel mehrere Monate." },
      { question: "Betreuen Sie auch Shopify-spezifische SEO-Themen?", answer: "Ja, inklusive Kategorien-, Filter- und Produktseitenstruktur sowie SEO-sicherer Migration." },
      { question: "Ersetzt KI-Sichtbarkeit klassisches SEO?", answer: "Nein, sie ergänzt es. Eine saubere technische und inhaltliche SEO-Basis bleibt Voraussetzung für Sichtbarkeit in beiden Systemen." },
    ],
    imagePlaceholders: {
      hero: {
        label: "Hero-Visual – SEO & KI-Sichtbarkeit",
        ratioDesktop: "21/9",
        ratioMobile: "4/5",
        motif: "Reduzierte, echte Datenvisualisierung einer Sichtbarkeits- oder Rankingentwicklung",
        wirkung: "sachlich, belastbar, präzise",
        funktion: "unterstreicht den messbaren Charakter der Leistung",
        type: "Grafik",
        mobileNote: "Kurve auf den relevanten Zeitraum zuschneiden",
      },
      application: {
        label: "Anwendungsbeispiel – Themencluster-Struktur",
        ratioDesktop: "16/9",
        ratioMobile: "4/5",
        motif: "Eigene Visualisierung eines Themenclusters mit Pillar-Page und unterstützenden Artikeln",
        wirkung: "strukturiert, nachvollziehbar",
        funktion: "erklärt die inhaltliche Herangehensweise visuell",
        type: "Grafik",
        mobileNote: "Cluster als vertikale Liste statt Netzdiagramm darstellen",
      },
      process: {
        label: "Prozessdarstellung – Vom Audit zur laufenden Betreuung",
        ratioDesktop: "16/9",
        ratioMobile: "1/1",
        motif: "Eigenes Diagramm der vier Prozessschritte",
        wirkung: "ruhig, verlässlich",
        funktion: "gibt Orientierung über den fortlaufenden Charakter von SEO",
        type: "Grafik",
        mobileNote: "Vertikale Anordnung der Phasen",
      },
    },
  },
  {
    slug: "google-ads-performance",
    category: "Sichtbarkeit & Marketing",
    navLabel: "Google Ads & Performance",
    menuDescription: "Kampagnen mit sauberem Tracking und klarer Wirkung.",
    h1: "Google Ads und Performance Marketing mit sauberer Erfolgsmessung",
    metaTitle: "Google-Ads-Agentur Köln | Performance Marketing | ONSET.digital",
    metaDescription:
      "Google-Ads-Agentur für Search, Shopping und Performance Max: strukturierte Kampagnenstrategie, sauberes Tracking und laufende Optimierung statt Blackbox-Reporting.",
    primaryKeyword: "Google-Ads-Agentur Köln",
    secondaryKeywords: ["Google Search Ads", "Google Shopping", "Performance Max", "Performance-Marketing-Agentur", "Tracking und Conversion-Messung"],
    heroKicker: "Google Ads & Performance Marketing",
    heroLead:
      "Performance Marketing ist nur so gut wie sein Tracking. Wir bauen Kampagnenstrategie und Erfolgsmessung gemeinsam auf, damit jede Investition nachvollziehbar bleibt.",
    audience: [
      "E-Commerce-Unternehmen mit Skalierungsbedarf bei Google Shopping und Search",
      "B2B-Unternehmen mit erklärungsbedürftigen Angeboten und langen Vertriebszyklen",
      "Unternehmen, deren bisheriges Kampagnen-Reporting keine belastbaren Aussagen zulässt",
    ],
    problems: [
      { title: "Kampagnen laufen ohne sauberes Tracking", description: "Conversions werden unvollständig oder fehlerhaft erfasst, Optimierung erfolgt auf unsicherer Datenbasis." },
      { title: "Landingpages passen nicht zur Anzeige", description: "Kampagnenbudget wird auf Seiten gelenkt, die die Suchintention nicht erfüllen." },
      { title: "Reporting bleibt intransparent", description: "Kennzahlen werden geliefert, aber wirtschaftliche Zusammenhänge bleiben unklar." },
    ],
    consequences:
      "Ohne sauberes Tracking lassen sich Kampagnen nicht wirtschaftlich sinnvoll skalieren. Jede Optimierung basiert dann auf Vermutungen statt auf belastbaren Daten – mit entsprechendem Streuverlust im Budget.",
    deliverables: [
      { title: "Kampagnenstrategie", description: "Struktur und Budgetverteilung über Search, Shopping und Performance Max entlang Ihrer Vertriebslogik." },
      { title: "Tracking- und Conversion-Messung", description: "Sauberer Aufbau von Conversion-Tracking als Voraussetzung jeder Optimierung." },
      { title: "Landingpage-Optimierung", description: "Abstimmung von Anzeige und Zielseite auf dieselbe Suchintention." },
      { title: "Laufende Kampagnenbetreuung", description: "Kontinuierliche Optimierung von Geboten, Anzeigen und Zielgruppen auf Basis der Datenlage." },
    ],
    approach:
      "Bevor wir Budget in Kampagnen investieren, stellen wir sicher, dass jede Conversion sauber gemessen wird. Erst auf dieser Grundlage lassen sich Kampagnen verantwortungsvoll skalieren.",
    process: [
      { title: "Tracking-Audit", description: "Prüfung und Korrektur bestehender Tracking- und Attributionssysteme." },
      { title: "Kampagnenstrategie", description: "Struktur, Zielgruppen und Budgetlogik werden entlang Ihrer Vertriebsziele festgelegt." },
      { title: "Umsetzung & Landingpages", description: "Kampagnenaufbau inklusive passender Zielseiten für jede Anzeigengruppe." },
      { title: "Laufende Optimierung", description: "Regelmäßige Anpassung auf Basis von Performance-Daten und wirtschaftlichen Zielgrößen." },
    ],
    systems: ["Google Ads (Search, Shopping, Performance Max)", "Google Tag Manager und Conversion-Tracking", "Analytics- und Attributionsmodelle", "Landingpage- und CRM-Anbindung"],
    advantages: [
      "Sauberes Tracking als Voraussetzung statt Kür",
      "Landingpages und Kampagnen aus einer Verantwortung",
      "Transparentes, wirtschaftlich lesbares Reporting",
      "Skalierung erst nach belastbarer Datenlage",
    ],
    relatedServiceSlugs: ["seo-ki-sichtbarkeit", "webdesign-webentwicklung", "branding-content"],
    relatedSolutionSlugs: ["e-commerce-unternehmen"],
    caseStudySlug: "beispielprojekt-platzhalter",
    insightSlugs: [],
    primaryCTA: "Kampagnenpotenzial besprechen",
    secondaryCTA: "Erstgespräch vereinbaren",
    faqs: [
      { question: "Ab welchem Budget lohnt sich Google Ads?", answer: "Entscheidender als die absolute Höhe ist eine saubere Tracking- und Landingpage-Basis. Den passenden Budgetrahmen besprechen wir im Erstgespräch." },
      { question: "Übernehmen Sie auch das Tracking-Setup?", answer: "Ja, sauberes Tracking ist fester Bestandteil jeder Kampagnenbetreuung, nicht optional." },
      { question: "Arbeiten Sie auch mit bestehenden Landingpages?", answer: "Wir prüfen zunächst, ob bestehende Seiten zur Suchintention passen, und optimieren oder ergänzen sie gezielt." },
      { question: "Wie sieht Ihr Reporting aus?", answer: "Wirtschaftlich lesbar und auf die für Sie relevanten Kennzahlen reduziert, keine reinen Klick- oder Impressionsreports." },
    ],
    imagePlaceholders: {
      hero: {
        label: "Hero-Visual – Google Ads & Performance",
        ratioDesktop: "21/9",
        ratioMobile: "4/5",
        motif: "Reale, anonymisierte Kampagnenstruktur oder Performance-Auswertung in reduzierter Darstellung",
        wirkung: "nachvollziehbar, seriös",
        funktion: "unterstreicht den datengetriebenen Charakter der Leistung",
        type: "Grafik",
        mobileNote: "Auf die zentrale Kennzahl fokussieren",
      },
      application: {
        label: "Anwendungsbeispiel – Kampagnenstruktur",
        ratioDesktop: "16/9",
        ratioMobile: "4/5",
        motif: "Vereinfachte, anonymisierte Darstellung einer Kampagnenstruktur über Search, Shopping und Performance Max",
        wirkung: "klar, strukturiert",
        funktion: "macht die strategische Herangehensweise sichtbar",
        type: "Grafik",
        mobileNote: "Struktur vertikal stapeln",
      },
      process: {
        label: "Prozessdarstellung – Vom Tracking-Audit zur Optimierung",
        ratioDesktop: "16/9",
        ratioMobile: "1/1",
        motif: "Eigenes Diagramm der vier Prozessschritte",
        wirkung: "ruhig, verlässlich",
        funktion: "gibt Orientierung über den fortlaufenden Charakter der Betreuung",
        type: "Grafik",
        mobileNote: "Vertikale Anordnung der Phasen",
      },
    },
  },
  {
    slug: "branding-content",
    category: "Sichtbarkeit & Marketing",
    navLabel: "Branding & Content",
    menuDescription: "Markenstrategie, Corporate Design und Content.",
    h1: "Branding und Content für Marken mit klarer Haltung",
    metaTitle: "Branding-Agentur Köln | Markenstrategie | ONSET.digital",
    metaDescription:
      "Markenstrategie, Corporate Design und Content-Strategie: Wir entwickeln eine visuelle und inhaltliche Identität, die zu Website, Shop und Marketing konsistent passt.",
    primaryKeyword: "Branding-Agentur Köln",
    secondaryKeywords: ["Markenstrategie-Agentur", "Corporate Design", "visuelle Markenidentität", "Content-Strategie"],
    heroKicker: "Branding & Content",
    heroLead:
      "Eine Marke, die nicht konsistent auftritt, verschenkt Vertrauen. Wir entwickeln Markenstrategie, Corporate Design und Content so, dass sie zu jedem digitalen Berührungspunkt passen.",
    audience: [
      "Unternehmen mit uneinheitlichem Auftritt über Website, Shop und Social Media",
      "Marken vor einem Rebranding oder einer strategischen Repositionierung",
      "Unternehmen, deren Content-Produktion ohne erkennbare Linie läuft",
    ],
    problems: [
      { title: "Uneinheitlicher Markenauftritt", description: "Website, Verpackung, Social Media und Vertriebsunterlagen wirken wie unterschiedliche Unternehmen." },
      { title: "Positionierung ist nicht klar formuliert", description: "Es fehlt eine eindeutige Antwort darauf, wofür die Marke steht und wen sie anspricht." },
      { title: "Content ohne strategische Linie", description: "Es wird produziert, aber ohne klaren Beitrag zu Positionierung oder Geschäftszielen." },
    ],
    consequences:
      "Eine uneinheitliche Markenwirkung schwächt Vertrauen in genau dem Moment, in dem Entscheidungen getroffen werden. Content ohne strategische Linie bindet Ressourcen, ohne messbar auf Sichtbarkeit oder Positionierung einzuzahlen.",
    deliverables: [
      { title: "Markenstrategie", description: "Positionierung, Zielgruppenverständnis und Markenversprechen als Grundlage aller weiteren Gestaltung." },
      { title: "Corporate Design", description: "Visuelle Identität inklusive Logo, Typografie und Anwendungssystem für digitale und physische Berührungspunkte." },
      { title: "Content-Strategie", description: "Themenplanung und Formate, die konsequent auf Positionierung und Geschäftsziele einzahlen." },
      { title: "Kampagnenkonzeption", description: "Inhaltliche und gestalterische Konzepte für Produkt- oder Markenkampagnen." },
    ],
    approach:
      "Wir entwickeln Design nicht losgelöst von Strategie: Positionierung und Zielgruppenverständnis stehen vor der visuellen Gestaltung, damit jedes gestalterische Element eine inhaltliche Begründung hat.",
    process: [
      { title: "Positionierungsworkshop", description: "Gemeinsame Klärung von Markenkern, Zielgruppe und Differenzierung." },
      { title: "Strategie & Konzept", description: "Ableitung von Markenbotschaft, Tonalität und gestalterischer Richtung." },
      { title: "Gestaltung & Anwendung", description: "Entwicklung des Corporate Designs und seiner Anwendung auf allen relevanten Kanälen." },
      { title: "Content-Umsetzung", description: "Laufende inhaltliche Produktion entlang der definierten Content-Strategie." },
    ],
    systems: ["Design- und Brand-Guideline-Systeme", "Content-Planungstools", "Digital-Asset-Management", "Schnittstellen zu Website, Shop und Social-Media-Kanälen"],
    advantages: [
      "Strategie vor Gestaltung, nicht umgekehrt",
      "Konsistenz über alle digitalen und physischen Berührungspunkte",
      "Content mit klarem Beitrag zu Positionierung und Sichtbarkeit",
      "Anbindung an Website, Shop und Marketing aus einer Hand",
    ],
    relatedServiceSlugs: ["webdesign-webentwicklung", "seo-ki-sichtbarkeit", "digitalstrategie"],
    relatedSolutionSlugs: ["mittelstand", "website-relaunch"],
    caseStudySlug: "beispielprojekt-platzhalter",
    insightSlugs: [],
    primaryCTA: "Markenprojekt anfragen",
    secondaryCTA: "Erstgespräch vereinbaren",
    faqs: [
      { question: "Entwickeln Sie auch ein komplett neues Logo?", answer: "Ja, im Rahmen der Markenstrategie und des Corporate Designs, sofern die Positionierung dies erfordert." },
      { question: "Wie hängen Branding und Website-Projekt zusammen?", answer: "Im Idealfall entsteht das Corporate Design vor oder parallel zur Website, damit visuelle Identität und digitale Umsetzung konsistent bleiben." },
      { question: "Übernehmen Sie auch die laufende Content-Produktion?", answer: "Ja, im Rahmen planbarer Betreuungskontingente entlang der definierten Content-Strategie." },
      { question: "Wie lange dauert ein Markenstrategie-Projekt?", answer: "Für Positionierung und Corporate Design realistisch sechs bis zehn Wochen, abhängig vom Abstimmungsaufwand." },
    ],
    imagePlaceholders: {
      hero: {
        label: "Hero-Visual – Branding & Content",
        ratioDesktop: "21/9",
        ratioMobile: "4/5",
        motif: "Anwendung eines Corporate Designs auf mehreren Flächen (digital und physisch) in editorialer Komposition",
        wirkung: "hochwertig, konsistent, selbstbewusst",
        funktion: "zeigt die Wirkung konsistenter Markenführung über mehrere Berührungspunkte",
        type: "Fotografie",
        mobileNote: "Auf eine bis zwei Anwendungsflächen reduzieren",
      },
      application: {
        label: "Anwendungsbeispiel – Markensystem",
        ratioDesktop: "16/9",
        ratioMobile: "4/5",
        motif: "Typografie, Farbwelt und Logoanwendung eines realen Markensystems im Detail",
        wirkung: "präzise, durchdacht",
        funktion: "belegt gestalterische Sorgfalt im Detail",
        type: "Mock-up",
        mobileNote: "Einzelnes Detailelement statt Gesamtsystem zeigen",
      },
      process: {
        label: "Prozessdarstellung – Vom Workshop zur Umsetzung",
        ratioDesktop: "16/9",
        ratioMobile: "1/1",
        motif: "Eigenes Diagramm der vier Prozessschritte",
        wirkung: "ruhig, orientierend",
        funktion: "gibt Orientierung über den kreativen Prozess",
        type: "Grafik",
        mobileNote: "Vertikale Anordnung der Phasen",
      },
    },
  },
];

export const getServiceBySlug = (slug: string) => services.find((service) => service.slug === slug);
